DEBUG 2022-04-28 04:47:58.894 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-04-28 04:47:58.894 UTC: 	 Running on: Linux lxplus7104.cern.ch 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-04-28 04:47:58.895 UTC: 	 Executing command: 'status'
DEBUG 2022-04-28 04:47:58.898 UTC: 	 Found CRAB cache file /afs/cern.ch/user/m/mikumar/.crab3
ERROR 2022-04-28 04:47:58.924 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/mikumar/private/NanoAOD_new/CMSSW_10_6_24/src/PhysicsTools/NanoAODTools/crab/tree/crab_tw_antitop_Tree_UL2016preVFP
ERROR 2022-04-28 04:47:58.924 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/m/mikumar/private/NanoAOD_new/CMSSW_10_6_24/src/PhysicsTools/NanoAODTools/crab/tree/crab_tw_antitop_Tree_UL2016preVFP
INFO 2022-04-28 04:47:58.927 UTC: 	 Log file is /afs/cern.ch/work/m/mikumar/private/NanoAOD_new/CMSSW_10_6_24/src/PhysicsTools/NanoAODTools/crab/tree/crab.log
